# Generated by Django 2.1.2 on 2018-10-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0002_breeder_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='dor',
            field=models.DateField(blank=True, default='1984-09-05'),
            preserve_default=False,
        ),
    ]
